//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        public int ID_employee { get; set; }
        public Nullable<int> type_of_employee { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> id_passport_data { get; set; }
    
        public virtual List_of_position List_of_position { get; set; }
        public virtual Passport_data Passport_data { get; set; }
    }
}
